spring:
  config:
    activate:
      on-profile: "local"
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC-5
          batch_size: 10

environment:
  database-url: jdbc:mysql://localhost:3306/cliente
  database-username: cliente
  database-password: cliente